### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by OkuraSt** [MeoBeoI/Catify#2]
Hi, Im trying to run this on my machine but it fails on npm install with this error:

> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer material-ui@0.15.0 wants react@^15.0.0
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-router@2.4.0 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-tap-event-plugin@0.2.2 wants react@^0.14.0
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer redux-devtools@3.3.1 wants react@^0.14.0 || ^15.0.0-rc.1
npm ERR! peerinvalid Peer redux-devtools-dock-monitor@1.1.1 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer redux-devtools-log-monitor@1.0.11 wants react@^0.14.0 || ^15.0.0-0

npm ERR! Please include the following file with any support request:
npm ERR!     G:\JavascriptProjects\Catify\npm-debug.log

I think one of the dependencies needs to be changed, but i cant find out which one, can somebody help me.

Thanks in advance.

**Comment by MeoBeoI** [comment]
Which version of node are you using ?
You can use [n](https://www.npmjs.com/package/n) to manage NodeJs version and try to run in NodeJs v5.0

**Comment by OkuraSt** [comment]
Sorry for the late response, I was able to npm install it using node 5.0, but i see the notifications work only on Mac right? Regardless I was able to use some concepts on your code, thank you.

**Comment by MeoBeoI** [comment]
Thank for your response. It only works on Mac, but I think for Windows, just use another notification module, It will be OK 😎
My code still quite messy 😿 , hope to see your work soon.
I will close this issue.

**Comment by MeoBeoI** [comment]
closes #2
