### ISSUE TITLE
Javascript error occurred.

### ISSUE THREAD

**Issue by rawnly** [MeoBeoI/Catify#3]
Hello this is the error! **Macbook Air early 2014** with **Mac OS Sierra**
![schermata 2016-12-11 alle 12 43 52](https://cloud.githubusercontent.com/assets/16429579/21081074/2b7bb3b6-bfbf-11e6-8c00-a71f6a42b8be.png)
![schermata 2016-12-11 alle 12 44 50](https://cloud.githubusercontent.com/assets/16429579/21081075/3031a8ca-bfbf-11e6-8376-fdf72db1ac66.png)

Now i'll try to compile my self.

What can i do?
Thanks in advance.

**Comment by MeoBeoI** [comment]
Thanks for your report, recently I quite busy, I will get back and investigate about this ASAP, when I have time.
Is Spotify available  in your country ?
Sorry for this inconvenient,

**Comment by rawnly** [comment]
Yes is availbale, i'm in Italy, don't worry i'll wai the fix i like your project idea 😋
